site_name: Opsbox Plugins

nav:
  - Intro: 'index.md'
  - Available Plugins: plugins/available_plugins.md


plugins:
- monorepo

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences