site_name: Opsbox Plugins

nav:
  - Intro: 'index.md'
  - Making Plugins:
      - Basics: plugins/development_basics.md
      - Making Handlers: plugins/making_handlers.md
      - Making Providers: plugins/making_providers.md
      - Making Outputs: plugins/making_outputs.md
      - Making Checks: plugins/making_checks.md


plugins:
- monorepo

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences