site_name: Opsbox Plugins

nav:
  - Intro: 'index.md'
  - AWS:
    - Checks: '*include ./aws_rego/*checks/mkdocs.yml'
  - Outputs: '!include ./outputs/mkdocs.yml'
  - Assistants: '!include ./assistants/mkdocs.yml'


plugins:
- monorepo

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences