[project]
name = "opsbox-modules"
version = "0.1.2"
description = "Plugins for Opsbox"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = "==3.11.*"
dependencies = [
    "loguru>=0.7.2",
    "pydantic>=2.10.2",
    "pymdown-extensions>=10.12",
    "tqdm>=4.67.1",
]


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--ignore=./tests/integration"
]
pythonpath = [
  "."
]
