[info]
name = "azure_idle_instances"
module = "azure_idle_instances"
class_name = "IdleInstances"
type = "rego"
uses = ["rego", "ec2"]

[rego]
description = "Check for idle Azure VM instances."
rego_file = "azure_idle_instances.rego"