[info]
name = "unattached_eips"
module = "unattached_eips"
class_name = "UnattachedEips"
type = "input"
uses = ["general", "ec2"]

[rego]
description= "Check for Unattached EIPs."
rego_file= "unattached_eips.rego"
