[project]
name = "opsbox-ec2-unattached-eips"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = "==3.11.*"
dependencies = [
    "loguru>=0.7.2",
    "pluggy>=1.5.0",
]

[project.entry-points.'opsbox.plugins']
opsbox_ec2_unattached_eips = "unattached_eips.unattached_eips:UnattachedEips"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"unattached_eips" = ["*.rego", "manifest.toml"]
