[info]
name = "rds_old_snapshots"
module = "rds_old_snapshots"
class_name = "RDSOldSnapshots"
type = "input"
uses = ["rds", "general"]

[rego]
description = "Check for old snapshots."
rego_file = "rds_old_snapshots.rego"
gather_from = "rds"
