[info]
name = "elb_low_request_count"
module = "low_request_count"
class_name = "LowRequestCount"
type = "input"
uses = ["elb","general"]

[rego]
description = "Check for ELBs with low request counts."
rego_file = "low_request_count.rego"
