[project]
name = "opsbox-elb-low-request-counts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "loguru>=0.7.2",
    "pluggy>=1.5.0",
]


[project.entry-points.'opsbox.plugins']
opsbox_elb_low_request_counts = "low_request_counts.low_request_count:LowRequestCount"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"low_request_counts" = ["*.rego", "manifest.toml"]