[info]
name = "unused_buckets"
module = "unused_buckets"
class_name = "UnusedBuckets"
type = "input"
uses = ["general", "s3"]

[rego]
description = "Check for unused buckets"
rego_file = "unused_buckets.rego"
