[info]
name = "elb_no_healthy_targets"
module = "no_healthy_targets"
class_name = "NoHealthyTargets"
type="input"
uses = ["elb", "general"]

[rego]
description = "Check for no healthy targets in load balancers."
rego_file =  "no_healthy_targets.rego"