[project]
name = "opsbox-elb-no_healthy_targets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = "==3.11.*"
dependencies = [
    "loguru>=0.7.2",
    "pluggy>=1.5.0",
]


[project.entry-points.'opsbox.plugins']
opsbox-elb-no_healthy_targets = "no_healthy_targets.no_healthy_targets:NoHealthyTargets"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"no_healthy_targets" = ["*.rego", "manifest.toml"]