[info]
name = "unused_policies"
module = "unused_policies"
class_name = "UnusedIAMPolicies"
type = "rego"
uses = ["rego", "iam"]

[rego]
description = "Check for empty iam policies."
rego_file = "unused_policies.rego"
