[info]
name = "elb_high_error_rate"
module = "high_error_rate"
class_name = "HighErrorRate"
type = "input"
uses = ["general", "elb"]

[rego]
description = "Check for high AWS ELB error rates"
rego_file = "high_error_rate.rego"