[project]
name = "opsbox-elb-high-error-rate"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = "==3.11.*"
dependencies = [
    "loguru>=0.7.2",
    "pluggy>=1.5.0",
]

[project.entry-points.'opsbox.plugins']
opsbox_elb_high_error_rate = "high_error_rate.high_error_rate:HighErrorRate"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"high_error_rate" = ["*.rego", "manifest.toml"]