[info]
name = "ec2_idle_instances"
module = "idle_instances"
class_name = "IdleInstances"
type = "input"
uses = ["general", "ec2"]

[rego]
description = "Check for idle EC2 instances."
rego_file = "idle_instances.rego"