[info]
name = "idle_instances"
module = "idle_instances"
class_name = "IdleInstances"
type = "rego"
uses = ["rego", "ec2"]

[rego]
description = "Check for idle EC2 instances."
rego_file = "idle_instances.rego"