[info]
name = "mfa_enabled"
module = "mfa_enabled"
class_name = "IAMMFADisabled"
type = "input"
uses = ["general", "iam"]

[rego]
description = "Check for empty iam policies."
rego_file = "mfa_enabled.rego"
