[info]
name = "storage_class_usage"
module = "storage_class_usage"
class_name = "StorageClassUsage"
type = "input"
uses = ["general", "s3"]


[rego]
description = "Check for storage class percentile."
rego_file = "storage_class_usage.rego"
gather_from = "s3"