[project]
name = "opsbox-s3-storage-class-usage"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "boto3>=1.35.86",
    "loguru>=0.7.3",
    "pluggy>=1.5.0",
]

[project.entry-points.'opsbox.plugins']
opsbox_s3_storage_class_usage = "storage_class_usage.storage_class_usage:StorageClassUsage"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"s3_storage_class_usage" = ["*.rego", "manifest.toml"]
