[info]
name = "empty_storage"
module = "empty_storage"
class_name = "EmptyStorage"
type = "input"
uses = ["general", "rds"]

[rego]
description = "Check for empty RDS storages."
rego_file = "empty_storage.rego"
