[info]
name = "console_access"
module = "console_access"
class_name = "ConsoleAccessIAM"
type = "input"
uses = ["general", "iam"]

[rego]
description = "Check for empty iam policies."
rego_file = "console_access.rego"
