[info]
name = "elb_inactive_load_balancers"
module = "inactive_load_balancers"
class_name = "InactiveLoadBalancers"
type="input"
uses = ["elb", "general"]

[rego]
description = "Check for inactive load balancers."
rego_file =  "inactive_load_balancers.rego"