[project]
name = "opsbox-s3-object-last-modified"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = "==3.11.*"
dependencies = [
    "boto3>=1.35.86",
    "loguru>=0.7.3",
    "pluggy>=1.5.0",
]

[project.entry-points.'opsbox.plugins']
opsbox_s3_object_last_modified = "object_last_modified.object_last_modified:ObjectLastModified"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"object_last_modified" = ["*.rego", "manifest.toml"]